worker_processes auto;
events {
    worker_connections 1024;
}
http {
    include       mime.types;
    # default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;
    server {
        listen       80;
        server_name  localhost;
        root   /usr/share/nginx/html;

        index index.html;

        add_header Cross-Origin-Opener-Policy "same-origin";
        add_header Cross-Origin-Embedder-Policy "require-corp";

        location / {
          try_files $uri $uri/index.html /index.html;
        }

        location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        location ~* \.(wasm|js)$ {
            gzip_static on;
            expires off;
            add_header Cache-Control "no-cache";
        }
        error_page 500 502 503 504 /50x.html;
    }
}
